sudo: required

language: python

python:
  - "3.5"

install: 
  - "pip install -r requirements.txt"

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - flask db upgrade

script: 
  - python tests/test_routes.py
  - python tests/test_resource_manager.py
  - python tests/test_filteration.py
  - python tests/test_sorting.py
  - python tests/test_grouping.py
  - python tests/test_query_string_options.py
  - python tests/test_pagination.py