sudo: required

language: python

python:
  - "3.5"

env:
  - DATABASE_URL = postgres://postgres:@localhost:5434/test_db
  - FLASK_DEBUG = False
  - SECRET_KEY = 'qi8H8R7OM4xMUNMPuRAZxlY'
  - FLASK_APP = wsgi.py

install: 
  - "pip install -r requirements.txt"

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

script: python -m tests.test_resource