sudo: required

language: python

python:
  - "3.5"

install: 
  - "pip install -r requirements.txt"

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - flask db upgrade
script: python tests/test_resource.py