"""server_log_entity

Revision ID: ebe23804cce6
Revises: 51eb8036842c
Create Date: 2016-11-08 20:32:12.700138

"""

# revision identifiers, used by Alembic.
revision = 'ebe23804cce6'
down_revision = '51eb8036842c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('headers', sa.String(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_log')
    ### end Alembic commands ###
